sudo: required
services:
  - docker
  - postgresql


before_install:
  - pip --version
  - docker --version
  - docker-compose --version
  - docker ps

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER numu WITH PASSWORD 'numu';" -U postgres
  - docker-compose -f docker-compose.travis.yml pull
  - docker-compose -f docker-compose.travis.yml build

script:
  - docker-compose -f docker-compose.travis.yml run --user=root --rm api pytest

after_script:
  - docker-compose -f docker-compose.travis.yml down