sudo: required
services:
  - docker

before_install:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - pip --version
  - docker --version
  - docker-compose --version
  - docker ps

before_script:
  - docker-compose -f docker-compose.local.yml pull
  - docker-compose -f docker-compose.local.yml build

script:
  - docker-compose -f docker-compose.local.yml run --user=root --rm api pytest

after_script:
  - docker-compose -f docker-compose.local.yml down