version: '3'
services:
  api:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=main.py
      - NUMU_CONFIG=config/prod.py
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.numutracker.com
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - proxy
      - numunet

  postgres:
    image: postgres:10.4
    volumes:
      - numu_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=numu
      - POSTGRES_DB=numu
      - POSTGRES_PASSWORD=
      - PGDATA=/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=false
    ports:
      - "5432:5432"
    networks:
      - numunet
    restart: unless-stopped

  redis:
    image: redis
    command: redis-server --requirepass numu_tracker
    volumes:
      - numu_redis:/var/lib/redis/data
    networks:
      - numunet

volumes:
  numu_pgdata:
    driver: local
  numu_redis:
    driver: local

networks:
  numunet:
    driver: bridge
    external: false
  proxy:
    external: true
