version: '2'
services:
  api:
    restart: always
    build: .
    env_file:
      - docker.base.env
    #  - docker.local.env
    ports:
      - "80:80"
    networks:
      - numunet
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    volumes:
      - numu_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=numu
      - POSTGRES_DB=numutracker
      - POSTGRES_PASSWORD=
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - numunet
    restart: unless-stopped

volumes:
  numu_pgdata:
    driver: local

networks:
  numunet:
    driver: bridge