version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URI=postgresql://numu:numu@postgres/numu
    volumes:
      - ./:/opt/app
    ports:
      - "80:80"
    networks:
      - numu_net
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10.4
    volumes:
      - numu_pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=numu
      - POSTGRES_DB=numu
      - POSTGRES_PASSWORD=numu
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - numu_net

  redis:
    image: redis
    command: redis-server --requirepass numu
    volumes:
      - numu_redis:/var/lib/redis/data
    networks:
      - numu_net

volumes:
  numu_pgdata:
    driver: local
  numu_redis:
    driver: local

networks:
  numu_net:
    driver: bridge
    external: false