version: '3'
services:
  api:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=main.py
      - NUMU_CONFIG=config/prod.py
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.numutracker.com
      - traefik.docker.network=proxy
      - traefik.port=80
    networks:
      - proxy
      - numunet

  redis:
    image: redis
    command: redis-server --requirepass numu_tracker
    volumes:
      - numu_redis:/var/lib/redis/data
    networks:
      - numunet

volumes:
  numu_pgdata:
    driver: local
  numu_redis:
    driver: local

networks:
  numunet:
    driver: bridge
    external: false
  proxy:
    external: true
